[build]
    publish = "_out"
    command = "hugo --buildFuture"

[context.production.environment]
  HUGO_VERSION = "0.71.1"
  TZ = "Europe/Warsaw"

[context.deploy-preview]
    command = "hugo --buildFuture -b ${DEPLOY_PRIME_URL}"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.71.1"
  TZ = "Europe/Warsaw"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/.well-known/matrix/server"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
